[package]
name = "tcp_server"
version = "0.1.0"
authors = ["chenyouneng@huanyi.onaliyun.com <chenyouneng@huanyi.onaliyun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
